### ISSUE TITLE
Problem Description is not a problem

### ISSUE THREAD

**Issue by omltcat** [cer-hunter/OAR-CAS741#10]
> OAR is intended to classify the characters in images according to their corresponding English language alphabet characters. It should be able to do this and communicate to users the confidence level in how correctly it classified the image.

This is more of a solution than a problem. Here should be a high-level overview of what you want to solve, which justifies why you want to develop this software. 
I guess since you also stated "the project is also intended to be a useful tools for learning about image processing" before, you can try to incorporate problems related to that here as well.

**Comment by cer-hunter** [comment]
I expanded on the problem a little and added info about using it for teaching
