### ISSUE TITLE
SRS: Assumptions

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#11]
1. I think you are missing the assumption that there must be only 1 character in the user input image? You mention that it must be oriented, but I could still input a photo of a sentence?
2. I'm not sure [A1](https://github.com/cer-hunter/OAR-CAS741/blob/58f5c114f7a748084b6d010248d232cffd25380f/docs/SRS/SRS.tex#L435) is a valid assumption, it describes how you are going to accomplish pre-processing - which is not a concern for the SRS?
3. In A4 you use the word [legible](https://github.com/cer-hunter/OAR-CAS741/blob/58f5c114f7a748084b6d010248d232cffd25380f/docs/SRS/SRS.tex#L442), which seems a little vague, my opinion is that just saying it should be oriented properly is more clear (just a thought).
4. This one is just me being picky, but I would consider changing ["even spread"](https://github.com/cer-hunter/OAR-CAS741/blob/58f5c114f7a748084b6d010248d232cffd25380f/docs/SRS/SRS.tex#L440) to "balanced distribution", or "even distribution".
5. A3 has misspelled "program".

**Comment by cer-hunter** [comment]
1. Yep, missing that, adding it to both the assumptions and scope (see 3).
2. Reworded it slightly so now it just says that pre-processing is assumed completed before calculations occur
3. I like that idea updated A4 to "All input images will display one single, properly oriented character."
4. That's fair updated to "balanced distribution"
5. Thank you
