### ISSUE TITLE
SRS: Table 5

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#12]
Your table is small enough to remove the [landscape command](https://github.com/cer-hunter/OAR-CAS741/blob/58f5c114f7a748084b6d010248d232cffd25380f/docs/SRS/SRS.tex#L1007C2-L1007C2).

You shoudl probably remove `afterpage` as well.

**Comment by cer-hunter** [comment]
yep, thanks!
