### ISSUE TITLE
SRS: Are colour images supported?

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#14]
I'm not sure if you mentioned anything about RGB images. I think it would be easy for you to accept RGB and internally convert to greyscale as part of the pre-processing stage.

If that is the case, you should provide theory on how RGB is converted to grey scale

**Comment by cer-hunter** [comment]
Yes colour images will be supported, however conversion and pre-processing is out of scope (ill use supporting libraries for it) so I'll mention it in the scope section
