### ISSUE TITLE
SRS: Image scaling models missing

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#15]
You mention resizing/rescaling images, however, there is no theory related to that.

Normally it would be bi-linear interpolation, or cubic interpolation (depending on if you are down scaling or upscaling). See the [OpenCV docs](https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html) for details.

**Comment by cer-hunter** [comment]
Yeah to address this I'm going to take Phil's advice from [Issue 6](https://github.com/cer-hunter/OAR-CAS741/issues/6) and add all the pre-processing stuff to the scope section, it probably shouldn't be involved with the goals or assumptions in general.
