### ISSUE TITLE
VnV Review

### ISSUE THREAD

**Issue by cer-hunter** [cer-hunter/OAR-CAS741#16]
Hi Adrian,

Please review my [VnV Plan](https://github.com/cer-hunter/OAR-CAS741/blob/main/docs/VnVPlan/VnVPlan.pdf), and make issues regarding any improvements you think there is to make.

Thanks,
Hunter

**Comment by adrian-soch** [comment]
Good job with the VnV plan. I've created issues to track my comments and questions.
