### ISSUE TITLE
VnV Plan Review

### ISSUE THREAD

**Issue by cer-hunter** [cer-hunter/OAR-CAS741#17]
Hi Gaofeng,

Please review my [VnV Plan](https://github.com/cer-hunter/OAR-CAS741/blob/main/docs/VnVPlan/VnVPlan.pdf), and make issues regarding any improvements you think there is to make.

Thanks,
Hunter

**Comment by Zhou4truth** [comment]
Hi Hunter,
    Thanks for reaching out.
    After reading your Plan document, I think your VnV Plan is quite good. Only one issue is that the format of the references in the reference part should be made more uniform. All in all, I think you have done a great work on this plan.
Best,
Gaofeng
