### ISSUE TITLE
VnV Plan Review

### ISSUE THREAD

**Issue by cer-hunter** [cer-hunter/OAR-CAS741#18]
Hi Dr. Smith,

Please review my [VnV Plan](https://github.com/cer-hunter/OAR-CAS741/blob/main/docs/VnVPlan/VnVPlan.pdf)

Thanks,
Hunter

**Comment by smiths** [comment]
[Hunter_VnVPlan.pdf](https://github.com/cer-hunter/OAR-CAS741/files/14566725/Hunter_VnVPlan.pdf)

**Comment by cer-hunter** [comment]
Addressed with 5cefbf5 (subsequent commits are for formatting). Thanks again!
