### ISSUE TITLE
VnV Review #1 - Hard coded section references

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#19]
Internal references to sections/tables/etc. should use labels and proper links instead of hard coding the section #. 

Examples are:
- [Section 3](https://github.com/cer-hunter/OAR-CAS741/blob/9d3b8b4d6193d43f6826e5139185fd38c8011af3/docs/VnVPlan/VnVPlan.tex#L118)
- https://github.com/cer-hunter/OAR-CAS741/blob/9d3b8b4d6193d43f6826e5139185fd38c8011af3/docs/VnVPlan/VnVPlan.tex#L177

**Comment by cer-hunter** [comment]
Addressed by commit d9c9f35
