### ISSUE TITLE
VnV Review #2 - Implementation Verification Plan

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#20]
In:
https://github.com/cer-hunter/OAR-CAS741/blob/9d3b8b4d6193d43f6826e5139185fd38c8011af3/docs/VnVPlan/VnVPlan.tex#L175
'inconsistencies' is vague, I think the sentence still works if you just remove that.

**Comment by cer-hunter** [comment]
Addressed by commit d9c9f35
