### ISSUE TITLE
VnV Review #3 - Spelling/Grammar

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#21]
- 'Software' should be lower case? https://github.com/cer-hunter/OAR-CAS741/blob/9d3b8b4d6193d43f6826e5139185fd38c8011af3/docs/VnVPlan/VnVPlan.tex#L77
- This sentence is weird: https://github.com/cer-hunter/OAR-CAS741/blob/9d3b8b4d6193d43f6826e5139185fd38c8011af3/docs/VnVPlan/VnVPlan.tex#L177
- In: https://github.com/cer-hunter/OAR-CAS741/blob/9d3b8b4d6193d43f6826e5139185fd38c8011af3/docs/VnVPlan/VnVPlan.tex#L202
    Perhaps use 'All tests are automatic unless otherwise stated.'
- Use 'Figure \ref ...', not just the number. https://github.com/cer-hunter/OAR-CAS741/blob/9d3b8b4d6193d43f6826e5139185fd38c8011af3/docs/VnVPlan/VnVPlan.tex#L223

**Comment by cer-hunter** [comment]
Addressed by commit d9c9f35
