### ISSUE TITLE
MG + MIS Review

### ISSUE THREAD

**Issue by cer-hunter** [cer-hunter/OAR-CAS741#24]
Hi Adrian,

It's review time. Please take a look at my Module Guide and Module Interface Specification.

List the files:

- [MG](https://github.com/cer-hunter/OAR-CAS741/blob/main/docs/Design/SoftArchitecture/MG.pdf)
- [MIS](https://github.com/cer-hunter/OAR-CAS741/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by cer-hunter** [comment]
Okay heads-up its actually ready for review now

**Comment by adrian-soch** [comment]
Reviews are added, good job - document looks very clean. The use of types is useful and clear.
