### ISSUE TITLE
MG Review - Confusion Matrix Module

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#28]
The confusion matrix is a good way to analyze the results of your model ✅, however, there are many other metrics that are used and provided for free by sci-kit learn.

Perhaps it's worth changing this module to be more abstract, like `Metrics Module`? Or something that provides a confusion matrix, but also any other metrics you may want at some point (f1 score, accuracy, averaging over the classes - different ways to compute a lot of stuff lol).

**Comment by cer-hunter** [comment]
Addressed in Commit 6dc32ba
