### ISSUE TITLE
MG Review - Uses Diagram

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#29]
Just a little nit:
1) I think that crossed out line is redundant, since the module that is connected to that one, connects to it eventually
2) The background may as well match the same white as the document, but,  that's just a stylistic opinion
![image](https://github.com/cer-hunter/OAR-CAS741/assets/6884645/3292317b-5f74-43eb-824e-9fce8e307186)

**Comment by cer-hunter** [comment]
Addressed in Commit 6dc32ba
