### ISSUE TITLE
MIS Review: oarUtils

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#30]
Different font for function names is a nice touch, makes it easy to read. But, some of these function should have Exceptions. If `oarUtils` was to be used in another context, you may want to throw errors if I use the wrong datatype, or my matrix size is wrong etc.

Example: `gradientDescent` - If I pass a learning rate of zero, does that make sense? I should at least get a parameter warning (maybe).

**Comment by cer-hunter** [comment]
Updated by commit e436ce1
