### ISSUE TITLE
MIS Review: exported constants

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#31]
Some of your modules have exported constants, I think you may have intended them to be 'just' constants (or state vars). 
For example, in `train` you export `LAMBDA`, but does anyone else need lambda outside the training module? So maybe its more of a state variable that can be set/get by other modules or the user - but not really a constant, and not really exported.

I could be wrong, I did read the PDF rather quickly.

**Comment by cer-hunter** [comment]
Updated by commit e436ce1
