### ISSUE TITLE
MIS Review: gui exceptions

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#32]
With my experience, a lot of functions that deal with user input can experience some kind of exceptions. Perhaps a generic guiException can be added. And as you program, you may find that you are going to want to gracefully terminate from some random user induce error.

This issue is more of just a thought, not really suggesting you do anything - but keep it in mind. I have similar comments for some of the other modules, most modules will have some kind exception - especially when you imagine someone else using your modules in another project.

**Comment by cer-hunter** [comment]
Updated by commit e436ce1
