### ISSUE TITLE
SRS: Ambiguous statement in Section 4.1

### ISSUE THREAD

**Issue by adrian-soch** [cer-hunter/OAR-CAS741#5]
In section [4.1](https://github.com/cer-hunter/OAR-CAS741/blob/58f5c114f7a748084b6d010248d232cffd25380f/docs/SRS/SRS.tex#L342) the wording is a little ambiguous - can there be more than one character in the image?

Compared to the [User Responsibilities](https://github.com/cer-hunter/OAR-CAS741/blob/58f5c114f7a748084b6d010248d232cffd25380f/docs/SRS/SRS.tex#L309), which says it has to be an oriented letter, I feel like Section 4.1could be more specific.

**Comment by cer-hunter** [comment]
Yep updated
