### ISSUE TITLE
Assumption on capital letters

### ISSUE THREAD

**Issue by omltcat** [cer-hunter/OAR-CAS741#8]
A2: The dataset used for training the software model as described by IM1, will only contain labels of capital letter characters.

I think this should be an assumption on user input instead. After all, you are choosing the training dataset, which you can already make sure they are all capital letters. But you don't have control over what the user would input.

**Comment by cer-hunter** [comment]
That's fair, although A4 describes my user input, I think it's still worthwhile to make assumptions about the dataset because IM1 and all the GDs rely on a dataset
