### ISSUE TITLE
Requirement on input image format

### ISSUE THREAD

**Issue by omltcat** [cer-hunter/OAR-CAS741#9]
R1: Accept an input image in the following formats:
– PNG (Portable Net Graphics)
– JPEG (Joint Photographic Experts Group)
– BMP (Bitmap)
– preloaded training images

The last one is not a format.
Did you mean to say user can either upload an image in format {PNG, JPEG, BMP}, or designate a preloaded imaged to be used?

**Comment by cer-hunter** [comment]
yeah but honestly after thinking about it I'm just going to remove that one
